**Chapter 3 - Exercise 3.21**

In [1]:
import numpy as np

In [14]:
# a) Since pa is the center of {c} frame seen from a
#    we have de translation a_t_c. The transformation
#    matrix a_T_b is also given, so:

a_t_c = np.array([[0,800,0,1]]).T # in homogeneous coordinates
a_T_b = np.array([[0,-1,0,-100],
                  [1,0,0,300],
                  [0,0,1,500],
                  [0,0,0,1]])

# rb = b_t_c = b_T_a @ a_t_c
rb = np.linalg.inv(a_T_b) @ a_t_c

print(f'a) rb =\n{rb}')

# b) Since the y and z axis from {a} and {c} frames are coplanar
#    its possible to identify the rotation matrix a_R_c as a
#    Rot(x,30°) on {a}'s x axis. Therefore, it's possible to find a_T_c
#    and then b_T_c

theta = np.deg2rad(30)
c = np.cos(theta)
s = np.sin(theta)

a_R_c = np.array([[1,0,0],
                  [0,c,-s],
                  [0,s,c]])

a_T_c = np.eye(4)
a_T_c[:3,:4] = np.concatenate((a_R_c,a_t_c[:3]),axis=1)

b_T_c = np.linalg.inv(a_T_b) @ a_T_c

print(f'\nb) b_T_c =\n{b_T_c}')

a) rb =
[[ 500.]
 [-100.]
 [-500.]
 [   1.]]

b) b_T_c =
[[ 0.00000000e+00  8.66025404e-01 -5.00000000e-01  5.00000000e+02]
 [-1.00000000e+00  0.00000000e+00  0.00000000e+00 -1.00000000e+02]
 [ 0.00000000e+00  5.00000000e-01  8.66025404e-01 -5.00000000e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
